name: e2e

on: [push]

jobs:
  run_e2e_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: manusa/actions-setup-minikube@v2.3.0
        with:
          minikube version: "v1.10.1"
          kubernetes version: "v1.18.2"
          github token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run e2e in k8s CI Cluster
        run: |
          MODE=ci ./example/deploy
